### ISSUE TITLE
Applicable to binary outcomes?

### ISSUE THREAD

**Issue by wilvancleve** [vdorie/bartCause#1]
I've been looking through this code, and I'm wondering if bartc can be used for causal inference on binary outcomes.

**Comment by vdorie** [comment]
Not at the moment. It wouldn't be hard to add but it should have some process for selecting the node standard deviation in the response model. I'm doing crossvalidation for the treatment model, but I want to transition to using a hyperprior instead and that will require modifications to the dbarts package.

**Comment by g-tierney** [comment]
Since this issue is still open, I just wanted to double check, does bartc work for binary outcomes now? 

It looks like there are some applications using it, but the Details section of bartc help file says "bartc represents a collection of methods that primarily use the Bayesian Additive Regression Trees (BART) algorithm to estimate causal treatment effects with binary treatment variables and **continuous outcomes**."

**Comment by vdorie** [comment]
Sorry for the slow response. It does work with binary outcomes. It does not work with continuous treatments (although there is no reason why it couldn't, given an appropriate estimand). I'll update the readme to reflect that.
